
# define web server
server {
    # listen for http req on 80
    listen 80;
    # directory containing compiled angular files
    root /usr/share/nginx/html;
    # default file to serve
    index index.html;

    # handle requests under /
    location / {
        # try the requested file or directory first if neither exist serve index.html
        try_files $uri $uri/ /index.html;
    }

    # match requests beginning with /api/
    location /api/ {
        # forward requests to spring boot service in docker compose on 8080
        # i.e. http://localhost/api/auth/me -> http://backend:8080/api/auth/me
        proxy_pass http://backend:8080;
    }
}