CREATE TABLE exercise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_date DATE NOT NULL,

    CONSTRAINT uk_workout_date
        UNIQUE (workout_date)
);

CREATE TABLE workout_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,

    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,

    weight NUMERIC(8, 2),
    unit VARCHAR(10) NOT NULL,

    notes VARCHAR(1000),
    position INTEGER NOT NULL,

    CONSTRAINT fk_workout_entry_workout
        FOREIGN KEY (workout_id)
        REFERENCES workout(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_workout_entry_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercise(id),

    CONSTRAINT uk_workout_entry_exercise
        UNIQUE (workout_id, exercise_id)
);