spring.datasource.url=jdbc:postgresql://localhost:5432/workout_tracker
spring.datasource.username=postgres
spring.datasource.password=88876839aA.

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.jpa.open-in-view=false